[tool.black]
line-length = 150
target-version = ["py310"]
include = '\.pyi?$'

[tool.ruff]
line-length = 150
exclude = [
    ".git",
    "__pycache__",
    "cache",
    "build",
    "dist",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "B", "UP", "W", "D"]
ignore = ["D203", "D213"]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
"test_*.py" = ["D"]

[tool.ruff.lint.isort]
known-first-party = ["histtext_toolkit"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

